# SET CONFIGURATION FOR CONNECTIONS WITH BIGQUERY
PROJECT_ID: PROJECT_ID  # Project ID in BIGQUERY
DATASET_NAME: DATASET_ID  # Dataset ID in BIGQUERY
TABLE_STATIONS: TABLE_STATIONS_ID # Table id with stations information in BIGQUERY
TABLE_MEASUREMENTS: TABLE_MEASUREMENTS_ID  # Table id with measurements in BIGQUERY
JSON_KEY_BQ: credentials.json # JSON key with credentials to BIGQUERY Project